name: deploy

on:
  workflow_call:
    inputs:
      deploy_target:
        required: true
        type: string
      target_file:
        required: true
        type: string
      dry_run:
        required: true
        type: boolean
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            echo "Deploying to ${{ inputs.deploy_target }} --file=${{ inputs.target_file }} --dry_run=${{ inputs.dry_run }}"
          else
            echo "Deploying to ${{ inputs.deploy_target }} --file=${{ inputs.target_file }}"
          fi
