name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened]

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
# is same as
# on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#
# not same as following (this means types: [])
#
# on:
#   pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: build
        run: |
          echo "Building..."
          # do something

  deploy:
    if: ${{ github.ref == 'release' || github.ref == 'main' }}
    needs: build
    strategy:
      matrix:
        include:
          - target: target_a
            target_file: a.json
          - target: target_b
            target_file: b.json
          - target: target_c
            target_file: c.json
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_target: ${{ matrix.target }}
      target_file: ${{ matrix.target_file }}
      dry_run: false

  deploy_dry_run:
    if: ${{ github.ref != 'release' && github.ref != 'main' }}
    needs: build
    strategy:
      matrix:
        include:
          - target: target_a
            target_file: a.json
          - target: target_b
            target_file: b.json
          - target: target_c
            target_file: c.json
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_target: ${{ matrix.target }}
      target_file: ${{ matrix.target_file }}
      dry_run: true
