name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [target_a, target_b, target_c]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run
        run: echo "Hello, world!"

      - if: "!contains(github.ref, 'release')"
        name: dry run deploy
        uses: ./.github/workflows/deploy@main
        with:
          deploy_target: ${{ matrix.target }}
          dry_run: true

      - if: "contains(github.ref, 'release')"
        name: deploy
        uses: ./.github/workflows/deploy@main
        with:
          deploy_target: ${{ matrix.target }}
          dry_run: false
