name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: |
          echo "Building..."
          # do something

  deploy:
    needs: build
    strategy:
      matrix:
        include:
          - target: target_a
            target_file: a.json
          - target: target_b
            target_file: b.json
          - target: target_c
            target_file: c.json

    uses: ./.github/workflows/deploy.yml
    with:
      deploy_target: target_a
      target_file: a.json
      dry_run: ${{ !contains(github.ref, 'release') }}
