name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: |
          echo "Building..."
          # do something

  deploy:
    needs: build
    strategy:
      matrix:
        target: [target_a, target_b, target_c]
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_target: target_a
      dry_run: ${{ !contains(github.ref, 'release') }}
