name: Spellcheck
on:
  pull_request:
    types: [opened, synchronize, reopened]

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
# is same as
# on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#
# not same as following (this means types: [])
#
# on:
#   pull_request:

permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check spelling
        uses: crate-ci/typos@master
        # typos is a Source code spell checker
        # https://github.com/crate-ci/typos
